package com.vidivox.Generators;

import com.vidivox.view.WarningDialogue;

import java.io.*;
import java.nio.file.Files;
import java.util.Scanner;

/**
 * Created by Jayden on 9/10/2015.
 * This class keeps all the methods relating to the manifest file in one place.
 * The manifest is structured as follows:
 * Video File
 * Audio files, each on a new line
 */
//The project folder probably needs this too.
public class ManifestController {
    File manifest;
    public ManifestController(File projectDir){
        this.manifest = new File(projectDir.getAbsolutePath()+System.getProperty("file.separator")+"Manifest.vvx");
    }

    public void create() {
        try {
            manifest.createNewFile();
        }catch(IOException e){
            //This should be unreachable in the current build.
            WarningDialogue.genericError("A manifest file already exists for this project");
        }
    }

     public void setVideo(String videoName) throws FileNotFoundException {
         try {
             //Trim the manifest name from the path, returning the project directory.
             String path = manifest.getPath().substring(0,manifest.getPath().lastIndexOf(System.getProperty("file.separator")));
             File temporary = new File(path + System.getProperty("file.separator") + "Temp.vvx");
             temporary.createNewFile();
             Scanner s1 = new Scanner(manifest);
             PrintWriter w1 = new PrintWriter(temporary);
             //Add new video to top of file
             w1.println(videoName);
             //Skip video in old file
             if (s1.hasNextLine()) {
                 s1.nextLine();
             }
             //Add audio files to new manifest
             while (s1.hasNextLine()) {
                 w1.append(s1.nextLine());
             }
             w1.close();
             PrintWriter w2 = new PrintWriter(manifest);
             Scanner s2 = new Scanner(temporary);
             //Clear the file
             w2.print("");
             //Write the temporary values into the manifest.
             while (s2.hasNextLine()) {
                 w2.append(s2.nextLine());
             }
             w2.close();
             s2.close();
             Files.delete(temporary.toPath());
         }catch (IOException e){
             //This should be unreachable, unless a temporary file already exists.
             new WarningDialogue("This project already contains a temporary file, not generated by Vidivox. Please remove it, then try again.");
         }
     }

    public String getVideo() throws FileNotFoundException {
        Scanner r = new Scanner(manifest);
        return r.nextLine();
    }

    public void addAudio(String audioName) throws FileNotFoundException {
        try {
            FileWriter w = new FileWriter(manifest,true);
            w.append("\n"+audioName);
            w.close();
        }catch(IOException e){
            //This should be unreachable.
            new WarningDialogue("A manifest error has occurred. Try reopening the project.");
        }
    }

}
